---
 - name: Delete application network
   docker_network:
     name: "{{ application_network }}"
     state: "{{ desired_state }}"

 - name: Delete MariaDB container
   docker_container:
     name: "mariadb{{ build_tag }}"
     state: "{{ desired_state }}"

 - name: Delete HRM container
   docker_container:
     name: "orange-hrm{{ build_tag }}"
     state: "{{ desired_state }}"