jenkins:
  systemMessage: "Welcome to the demo Jenkins IaC setup"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
        - id: "creator"
          password: "creator"
        - id: "user"
          password: "user"

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "Administrators"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "Creators"
            description: "Job creators"
            permissions:
              - "Overall/Read"
              - "Job/Create"
              - "Job/Build"
              - "Job/Cancel"
            assignments:
              - "creator"
          - name: "Users"
            description: "Authorized users"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Cancel"
            assignments:
              - "authenticated"
          - name: "Unauthorized"
            description: "Authorized users"
            permissions:
              - "Overall/Read"
            assignments:
              - "anonymous"

  clouds:
    - docker:
        name: docker-on-docker
        dockerApi:
          dockerHost:
            uri: tcp://dproxy:2375
        templates:
          - labelString: "docker-agent"
            dockerTemplateBase:
              image: "jenkins/slave"
            remoteFs: "/home/jenkins/agent"
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "10"
            retentionStrategy:
              idleMinutes: 5
            removeVolumes: true

jobs:
  - script: >
      pipelineJob('integration-pipeline') {
          definition {
              cpsScm {
                  scriptPath('pipeline-config/Jenkinsfile')
                  lightweight(true)
                  scm {
                      git {
                          remote {
                              url 'https://github.com/ehabibov/jenkins-iac-ci.git'
                          }
                      branch 'master'
                      }
                  }
              }
          }
      }

tool:
  maven:
    installations:
      - name: "Maven3"
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.6.6"
  allure:
    installations:
      - name: "Allure2"
        properties:
          - installSource:
              installers:
                - allureCommandlineInstaller:
                    id: "2.13.2"
  ansibleInstallation:
    installations:
      - name: "ansible-master"
        home: "/usr/bin"

unclassified:
  simple-theme-plugin:
    elements:
      - cssUrl:
          url: "http://afonsof.com/jenkins-material-theme/dist/material-teal.css"

groovy:
  - script: >
      import jenkins.model.Jenkins;
      import hudson.plugins.locale.PluginImpl;
      PluginImpl localePlugin = (PluginImpl) Jenkins.instance.getPlugin("locale");
      localePlugin.systemLocale = "en_US";
      localePlugin.@ignoreAcceptLanguage=true;