---
 - name: Create Selenoid network
   docker_network:
     name: "{{ selenoid_network }}"

 - name: Create Selenoid container
   docker_container:
     name: "selenoid"
     image: "aerokube/selenoid:latest"
     networks:
       - name: "{{ selenoid_network }}"
     published_ports:
       - "{{ selenoid_host_port }}:{{ selenoid_container_port }}"
     command: ["-conf", "/etc/browsers.json",
               "-container-network", "{{ selenoid_network }}",
               "-video-output-dir", "/opt/selenoid/video",
               "-log-output-dir", "/opt/selenoid/logs",
               "-service-startup-timeout", "{{ service_startup_timeout }}",
               "-session-delete-timeout", "{{ session_delete_timeout }}",
               "-timeout", "{{ timeout }}",
               "-capture-driver-logs"]
     state: present

 - name: Copy 'browsers.json' to container
   shell: "docker cp {{ role_path }}/files/browsers.json selenoid:/etc"

 - name: Start Selenoid container
   docker_container:
     name: "selenoid"
     state: "{{ desired_state }}"
   register: selenoid_metadata

 - name: Run Selenoid UI container
   docker_container:
     name: "selenoid-ui"
     image: "aerokube/selenoid-ui:latest"
     detach: true
     networks:
       - name: "{{ selenoid_network }}"
     published_ports:
       - "{{ selenoid_ui_host_port }}:{{ selenoid_ui_container_port }}"
     state: "{{ desired_state }}"
     command: ["-selenoid-uri", "http://selenoid:{{ selenoid_container_port }}"]
   register: selenoid_ui_metadata