---
 - name: Delete Selenoid network
   docker_network:
     name: "{{ selenoid_network }}"
     state: "{{ desired_state }}"

 - name: Delete Selenoid container
   docker_container:
     name: "selenoid-{{ build_tag }}"
     state: "{{ desired_state }}"

 - name: Delete Selenoid UI container
   docker_container:
     name: "selenoid-ui-{{ build_tag }}"
     state: "{{ desired_state }}"