---
 - name: Create application network
   docker_network:
     name: "{{ application_network }}"

 - name: Attach Jenkins to application network
   docker_network:
     name: "{{ application_network }}"
     connected: "{{ jenkins_container }}"

 - name: Run MariaDB container
   docker_container:
     name: "mariadb{{ build_tag }}"
     image: "bitnami/mariadb:10.2"
     networks:
       - name: "{{ application_network }}"
     published_ports:
       - "{{ mariadb_host_port }}:{{ mariadb_container_port }}"
     env:
       MARIADB_USER: "bn_orangehrm"
       MARIADB_DATABASE: "bitnami_orangehrm"
       ALLOW_EMPTY_PASSWORD: "yes"
     state: started
     recreate: true
     memory: 2G
   register: db_container_metadata

 - name: Wait for MySQL to accept connections
   wait_for:
     host: "{{ db_container_metadata['ansible_facts']['docker_container']['NetworkSettings']['IPAddress'] }}"
     port: "{{ mariadb_host_port }}"
     state: drained
     connect_timeout: 1
     timeout: 30
   register: mariadb_running
   until: mariadb_running is success
   retries: 10
   tags: mysql-wait

 - name: Run HRM container
   docker_container:
     name: "orange-hrm{{ build_tag }}"
     image: "bitnami/orangehrm:4.3.4-0-debian-10-r22"
     networks:
       - name: "{{ application_network }}"
     published_ports:
       - "{{ hrm_http_host_port }}:{{ hrm_http_container_port }}"
       - "{{ hrm_https_host_port }}:{{ hrm_https_container_port }}"
     env:
       MARIADB_HOST: "mariadb{{ build_tag }}"
       MARIADB_PORT_NUMBER: "{{ mariadb_container_port }}"
       ORANGEHRM_DATABASE_USER: "bn_orangehrm"
       ORANGEHRM_DATABASE_NAME: "bitnami_orangehrm"
       ALLOW_EMPTY_PASSWORD: "yes"
     state: started
     recreate: true
     memory: 2G
   register: hrm_container_metadata

 - name: Wait for HRM to be installed
   uri:
     url: "http://orange-hrm{{ build_tag }}:{{ hrm_http_container_port }}"
     status_code: 200
   register: result
   until: result.status == 200
   retries: 60
   delay: 5
