version: '3.6'

services:
  jenkins:
    build: jenkins-server
    image: jenkins-ci/ehabibov:1.0
    container_name: 'jenkins_ci'
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jcasc-config
    ports:
      - '9080:8080'
      - '50000:50000'
    volumes:
      - './volumes/jenkins:/var/jenkins_home'
      - '../jcasc-config:/var/jenkins_home/jcasc-config'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - jenkins-net

  proxy:
    build: docker-proxy
    image: jenkins-ci/docker-proxy:1.0
    container_name: 'proxy'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      jenkins-net:
        aliases:
          - dproxy

networks:
  jenkins-net:
    driver: bridge