---
- hosts: this_machine
  vars:
    build_tag: "--{{ lookup('env','BUILD_TAG') | default('na', true) }}"
    application_network: infrastructure-net
  roles:
    - role: install-application-cluster
      vars:
        mariadb_host_port: "3306"
        mariadb_container_port: "3306"
        hrm_http_host_port: "8080"
        hrm_http_container_port: "80"
        hrm_https_host_port: "443"
        hrm_https_container_port: "443"
        desired_state: started
      tags: app-deploy
    - role: destroy-application-cluster
      vars:
        desired_state: absent
      tags: app-destroy