---
 - name: Create application network
   docker_network:
     name: 'hrm-net'
   tags: install

 - name: Run MariaDB container
   docker_container:
     name: 'mariadb'
     image: 'bitnami/mariadb:10.2'
     networks:
       - name: 'hrm-net'
     published_ports:
       - '3306:3306'
     env:
       MARIADB_USER: 'bn_orangehrm'
       MARIADB_DATABASE: 'bitnami_orangehrm'
       ALLOW_EMPTY_PASSWORD: 'yes'
     state: started
   register: db_container_metadata
   tags: install

 - name: Wait for MySQL to accept connections
   become: yes
   wait_for:
     host: '{{ db_container_metadata["ansible_facts"]["docker_container"]["NetworkSettings"]["IPAddress"] }}'
     port: 3306
     state: drained
     connect_timeout: 1
     timeout: 30
   register: mariadb_running
   until: mariadb_running is success
   retries: 10
   tags: install

 - name: Run HRM container
   docker_container:
     name: 'hrm'
     image: 'bitnami/orangehrm:4.3.4-0-debian-10-r22'
     networks:
       - name: 'hrm-net'
     published_ports:
       - '8080:80'
       - '443:443'
     env:
       MARIADB_HOST: 'mariadb'
       MARIADB_PORT_NUMBER: '3306'
       ORANGEHRM_DATABASE_USER: 'bn_orangehrm'
       ORANGEHRM_DATABASE_NAME: 'bitnami_orangehrm'
       ALLOW_EMPTY_PASSWORD: 'yes'
     state: started
   register: hrm_container_metadata
   tags: install

 - name: Wait for HRM to be installed
   uri:
     url: "http://127.0.0.1:8080"
     status_code: 200
   register: result
   until: result.status == 200
   retries: 60
   delay: 5
   tags: install